// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5110.YouTubeTry;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static AnalogPotentiometer armsPotentiometer;
    public static CANTalon armsCANTalonSRX;
    public static SpeedController driveTrainRightMotor;
    public static SpeedController driveTrainLeftMotor;
    public static RobotDrive driveTrainRobotDrive;
    public static Encoder elevatorQuadratureEncoder;
    public static CANTalon elevatorLiftmotor;
    public static CANTalon armWheelsRightWheel;
    public static CANTalon armWheelsLeftWheel;
    public static RobotDrive armWheelsArmWheels;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        armsPotentiometer = new AnalogPotentiometer(0, 1.0, 0.0);
        LiveWindow.addSensor("Arms", "Potentiometer", armsPotentiometer);
        
        armsCANTalonSRX = new CANTalon(2);
        // When I try to make this in the livewindow it gives me an error about the CANTalon.
        
        driveTrainRightMotor = new Talon(0);
        LiveWindow.addActuator("Drive Train", "Right Motor", (Talon) driveTrainRightMotor);
        
        driveTrainLeftMotor = new Talon(1);
        LiveWindow.addActuator("Drive Train", "Left Motor", (Talon) driveTrainLeftMotor);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainLeftMotor, driveTrainRightMotor);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);
        

        elevatorQuadratureEncoder = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("Elevator", "Quadrature Encoder", elevatorQuadratureEncoder);
        elevatorQuadratureEncoder.setDistancePerPulse(1.0);
        elevatorQuadratureEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        elevatorLiftmotor = new CANTalon(3);
        
        
        armWheelsRightWheel = new CANTalon(4);
        
        
        armWheelsLeftWheel = new CANTalon(5);
        
        
        armWheelsArmWheels = new RobotDrive(armWheelsLeftWheel, armWheelsRightWheel);
        
        armWheelsArmWheels.setSafetyEnabled(true);
        armWheelsArmWheels.setExpiration(0.1);
        armWheelsArmWheels.setSensitivity(0.5);
        armWheelsArmWheels.setMaxOutput(1.0);
        


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
